/* Write your T-SQL query statement below */




SELECT ROUND(SUM(TIV_2016),2) AS TIV_2016
FROM
(SELECT *,
COUNT(1) OVER(PARTITION BY TIV_2015) AS CNT1,
COUNT(1) OVER(PARTITION BY LAT, LON) AS CNT2
FROM INSURANCE
) AS TBL
WHERE CNT1 > =2 AND CNT2 =1